import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#151E2C",
        "surface-dim": "#1B263B",
        "surface-bright": "#3E4A61",
        "surface-container-lowest": "#101620",
        "surface-container-low": "#1B263B",
        
        "surface-container": "#202E44",
        "surface-container-high": "#2A3A55",
        "surface-container-highest": "#3E4A61",
        "on-surface": "#FFFFFF",
        "on-surface-variant": "#AAB8D5",
        "inverse-surface": "#FFFFFF",
        "inverse-on-surface": "#151E2C",
        outline: "#5E6C8A",
        "outline-variant": "#3E4A61",
        "surface-tint": "#F8C914",
        primary: "#F8C914",
        "on-primary": "#2A3A55",
        "primary-container": "#F8C914",
        "on-primary-container": "#2A3A55",
        "inverse-primary": "#151E2C",
        secondary: "#575e70",
        "on-secondary": "#ffffff",
        "secondary-container": "#d9dff5",
        "on-secondary-container": "#5c6274",
        tertiary: "#735c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#cea700",
        "on-tertiary-container": "#4e3e00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#c0c6db",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        "tertiary-fixed": "#ffe083",
        "tertiary-fixed-dim": "#eec200",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#574500",
        background: "#151E2C",
        "on-background": "#FFFFFF",
        "surface-variant": "#3E4A61",
        "success-green": "#25D366",
        "error-red": "#B20002",
        "surface-gray": "#1B263B",
        "border-subtle": "#2A3A55",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        grotesk: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
